name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Move to Api
      run: cd Api
    - name: ls
      run: ls
    - name: pwd
      run: pwd
    - name: Run docker
      run: cd Api && docker build .
